services:
  - type: web
    name: crypto-payment-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Add other environment variables here 